---
title: 不要用网络来消遣, 用什么来消遣?
author: ZERO
date: '2020-04-15'
slug: don-t-use-the-internet-for-entertainment
categories:
  - reading
tags:
  - deep work
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-15T07:07:20+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

> 脑力活动需要的是变化和切换, 不会感到疲倦

> 何为生活? 而不仅仅是生存

# 为什么不能用网络来消遣?

如何度过你的一天 24 小时, How To Live On 24 Hours A Day? 

尽管不太喜欢自己的这一天的生活, 但是还是把 8:30-17:30 这段时间当做是这一天的生活, 这之前的和之后的时间是这一天的前奏和尾声.


应该要像贵族一样使用自己的时间


娱乐时间仍然是堕落的, 主要是胡乱点击一些没有价值的数字娱乐信息

你应该能够主动利用自己工作外的时间和精力

减少网络工具对你深度工作能力的干扰

## 尽可能吸引你时间和注意力的网站

+ facebook
+ reddit
+ wechat
+ Twitter
+ 优酷
+ 爱奇艺
+ 哔哩哔哩
+ 抖音
+ 快手


这些网站的共同点: 使用精心雕琢的标题和容易理解的内容, 辅以数学算法打磨, 最大限度的吸引你的眼球

一周的工作时间结束, 这些网站就成了你的主要娱乐. 

这些事情都是损害你抵抗分心事物的能力, 使你在试图深度工作的时候更难集中注意力.

这些事情总是唾手可得, 让你即时满足.(也许增加这些事情获得难度是一个办法, 最小阻力之路)




# 用什么来消遣?

> 在你全部的清醒时间都给自己的大脑找到有意义的事情去做，而不是放任自己在迷糊的状态下漫无目的的浏览几个小时的网页，那么在这一天结束的时候，你会觉得更加充实，第2天开始也更加轻松。


## 核心思想


在你的娱乐时间做更多的思考, 主动思考我应该怎么度过这一天?

> 这些致瘾的网址只有在真空中才能生存: 如果你在某一段时间没有给自己安排任务, 这些网站总是一种有诱惑的选择. 如果你在自由时间有高质量的事情去做, 这些网站对你的注意力的控制就会减弱.


## 操作

在周末到来之前确定要做的事情是十分重要的

一些安排好的爱好为这些时间提供了充分的养料
为了特定的目标完成特定的活动, 这将填满你的时间

+ 阅读
+ 锻炼
+ 唱歌
+ 爱好
+ 新的技能
+ 和老友见面

# 总结

如果你想抵御娱乐网站对你时间和精力的诱惑，那么就给大脑找一些高质量的替代活动，这样不仅可以使我们避免分心，保持专注的能力，同时还有可能实现一个宏伟目标，体验到<font color="darkred">何为生活而不仅仅是生存</font>。









