---
title: Use selenium in python
author: ZERO
date: '2020-04-05'
slug: use-selenium-in-python
categories:
  - Tools
tags:
  - spider
  - python
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-05T19:36:57+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

<!-- --- -->
<!-- title: "hello world" -->
<!-- description: | -->
<!--   Taking the `radix` R package for a test spin with `Scikit Learn`! -->
<!-- author: -->
<!--   - name: Jixing Liu -->
<!--     url: https://jixing.netlify.com/ -->
<!--     affiliation: DeepDrug -->
<!--     affiliation_url: http://www.deepdrug.cn/en/ -->
<!-- date: "`r Sys.Date()`" -->
<!-- #bibliography: biblio.bib   -->
<!-- output: -->
<!--   radix::radix_article: -->
<!--     toc: true -->
<!--     toc_depth: 3 -->
<!--     number_sections: true -->
<!--     self_contained: true -->
<!-- --- -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,      # Output code chunks
    message = FALSE,  # Toggle off message output 
    warning = FALSE)  # Toggle off warning output
knitr::opts_knit$set(root.dir = usethis::proj_path())
library(docknitr)

library(tidyverse)
theme_set(theme_light())
```

```{r}
library(reticulate)
reticulate::use_python("/Users/zero/anaconda3/envs/reticulate/bin/python3")
```


