---
title: Principle of least resistance
author: ZERO
date: '2020-04-16'
slug: principle-of-least-resistance
categories:
  - reading
tags:
  - deep work
subtitle: ''
summary: ''
authors: []
lastmod: '2020-04-16T07:40:24+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,      # Output code chunks
    message = FALSE,  # Toggle off message output 
    warning = FALSE)  # Toggle off warning output
knitr::opts_knit$set(root.dir = usethis::proj_path())
library(docknitr)

library(tidyverse)
theme_set(theme_light())
```

> 在缺乏度量或及时反馈的环境下, 大多数人都会选择最简单的行为和事情来做。


## 什么是最小阻力原则

> 最小阻力原则: 是指在工作环境下, 若各种行为对于底线的影响<font color="darkred"> __没有得到明确的反馈意见__</font> , 那我们则倾向于采用当下最简单易行的行为。



## 保持联结状态真的有助于工作?

答案是否定的.

为了验证这个想法, 波士顿咨询集团采用了一些极端手段, 他迫使团队中每一名成员在工作日中选择一天不上班, 也就是说和公司内外的任何人都断开联系.

最初这个团队有些抵制这项实验, 据他回忆, 其中一些尝试负责的合伙人一直对我们的基本观点很支持, 但是这时也突然有些紧张, 害怕告诉客户, 他团队中的每一个成员每周都有一天不工作, 那些咨询员也同样很紧张担忧他们这样会置事业于危机, 但是这个团队并没有失去客户, 团队成员也没有丢掉工作, 相反这些咨询员在工作中找到了更多的乐趣, 内部的沟通也更顺畅, 也学到了更多的东西。或许最重要的是为客户提供更好的产品。

## 为什么联结文化经久不衰?

一个有趣的问题: 为什么有那么多的公司像波士顿咨询集团一样培育一种连接的文化, 尽管在他的研究中发现, 此举会损害员工的幸福感和生产效率, 且很可能无助于提高底.

<font color="darkred"> __答案是这样更简单__</font> , 原因有二:

+ 原因一,关乎于对个人需求的响应, 如果你所处的工作环境下提出问题能够立刻得到答案, 需要某一特定信息能够立刻得到(即时满足), 那么你的生活就会变得更简单, 至少在当时是这样的, 如果无法得到这样迅速的响应, 你就需要做更多的预先工作和计划, 需要根据条理性, 同时还要时刻准备暂时搁置工作, 将注意力转移到别处, 等待所有要求达成(延时满足), 所有的这些都将使你的日常工作生活更加艰难, 尽管从长期来讲这样做更能令人满意, 但是我们不想这么复杂。

+ 原因二, 在于它可以创造出一种环境, 在这种环境下利用收件箱管理一天的工作是可以被接受的, 欣然回复最新的邮件, 其他的则堆积在那里, 同时还感觉自己的效率令人满意, 如果将电子邮件转移为边远工作, 你就需要采用一种更深思熟虑的方式, 理清下一步的工作内容以及工作时长, 这种计划是很困难的。


## 例会的困境

项目上频繁召开的例会, 这些会议往往使你无法持续专注, 导致日程无法及时完成, 变得支离破碎, 为什么还要坚持呢？

因为更简单, 对于很多人而言, 这些例会是一种简单的(但同时也是笨拙的人员管理形式), 他们不愿意自己去管理时间和工作任务, 而是让每周迫近的例会迫使他们在给定项目上采取一些行动或者提供<font color="darkred"> __一种取得进展的可视化幻象__</font> 。

## 负面影响

> 最小阻力原则受到度量黑洞的保护, 很少有人对其加以审视, 在这种原则支配下的工作文化免去了我们短期内保持专注合作计划的忧虑, 却牺牲了长期的满足感和真实价值的产出, 这样一来最小主力原则就驱使我们在深度工作愈发受到青睐的经济形势下流于浮浅工作。


## 解决办法


选择一件对你很重要的事情(这种事情一般是很难度量成功和即时反馈的), 设定一些小的虚拟反馈, 比如, 背了多少单词, 寄了多少分, 利用打游戏上瘾的一些原理来促进你在这些事情上取得推进.




